// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GistManager
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGistManagerWindowPackageString = "3ad644d8-5bf1-4188-b7f8-3be7a2fad242";
        public const string guidGistManagerWindowPackageCmdSetString = "201a26b6-c0e5-44c5-9d0f-840f00a17d1b";
        public const string guidImagesString = "cdabac7d-3b11-4f7a-914a-8183a71f9248";
        public static Guid guidGistManagerWindowPackage = new Guid(guidGistManagerWindowPackageString);
        public static Guid guidGistManagerWindowPackageCmdSet = new Guid(guidGistManagerWindowPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GistManagerWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
